export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const ALL_USERS = "ALL_USERS";
export const GET_USERS = "GET_USERS";
export const CREATE_USER = "CREATE_USER";
export const EDIT_USER = "EDIT_USER";
export const DELETE_USER = "DELETE_USER";
export const USER_DETAIL = "USER_DETAIL";

export const ALL_RECIVERS = "ALL_RECIVERS";
export const GET_RECIVERS = "GET_RECIVERS";
export const CREATE_RECIVER = "CREATE_RECIVER";
export const EDIT_RECIVER = "EDIT_RECIVER";
export const DELETE_RECIVER = "DELETE_RECIVER";
export const RECIVER_DETAIL = "RECIVER_DETAIL";

export const ALL_ADRESSES = "ALL_ADRESSES";
export const GET_ADRESSES = "GET_ADRESSES";
export const CREATE_ADRESSE = "CREATE_ADRESSE";
export const EDIT_ADRESSE = "EDIT_ADRESSE";
export const DELETE_ADRESSE = "DELETE_ADRESSE";
export const ADRESSE_DETAIL = "ADRESSE_DETAIL";

export const ALL_T_VEHICULES = "ALL_T_VEHICULES";
export const GET_T_VEHICULES = "GET_T_VEHICULES";
export const CREATE_T_VEHICULE = "CREATE_T_VEHICULE";
export const EDIT_T_VEHICULE = "EDIT_T_VEHICULE";
export const DELETE_T_VEHICULE = "DELETE_T_VEHICULE";
export const T_VEHICULE_DETAIL = "T_VEHICULE_DETAIL";

export const ALL_T_MARCHANDISES = "ALL_T_MARCHANDISES";
export const GET_T_MARCHANDISES = "GET_T_MARCHANDISES";
export const CREATE_T_MARCHANDISE = "CREATE_T_MARCHANDISE";
export const EDIT_T_MARCHANDISE = "EDIT_T_MARCHANDISE";
export const DELETE_T_MARCHANDISE = "DELETE_T_MARCHANDISE";
export const T_MARCHANDISE_DETAIL = "T_MARCHANDISE_DETAIL";

export const ALL_M_PAYEMENTS = "ALL_M_PAYEMENTS";
export const GET_M_PAYEMENTS = "GET_M_PAYEMENTS";
export const CREATE_M_PAYEMENT = "CREATE_M_PAYEMENT";
export const EDIT_M_PAYEMENT = "EDIT_M_PAYEMENT";
export const DELETE_M_PAYEMENT = "DELETE_M_PAYEMENT";
export const M_PAYEMENT_DETAIL = "M_PAYEMENT_DETAIL";

export const ALL_VEHICULES = "ALL_VEHICULES";
export const GET_VEHICULES = "GET_VEHICULES";
export const CREATE_VEHICULE = "CREATE_VEHICULE";
export const EDIT_VEHICULE = "EDIT_VEHICULE";
export const DELETE_VEHICULE = "DELETE_VEHICULE";
export const VEHICULE_DETAIL = "VEHICULE_DETAIL";

export const ALL_MARCHANDISES = "ALL_MARCHANDISES";
export const GET_MARCHANDISES = "GET_MARCHANDISES";
export const CREATE_MARCHANDISE = "CREATE_MARCHANDISE";
export const EDIT_MARCHANDISE = "EDIT_T_MARCHANDISE";
export const DELETE_MARCHANDISE = "DELETE_MARCHANDISE";
export const MARCHANDISE_DETAIL = "MARCHANDISE_DETAIL";

export const ALL_ANNONCES = "ALL_ANNONCES";
export const GET_ANNONCES = "GET_ANNONCES";
export const CREATE_ANNONCE = "CREATE_ANNONCE";
export const EDIT_ANNONCE = "EDIT_ANNONCE";
export const DELETE_ANNONCE = "DELETE_ANNONCE";
export const ANNONCE_DETAIL = "ANNONCE_DETAIL";

export const ALL_PROPOSITIONS = "ALL_PROPOSITIONS";
export const GET_PROPOSITIONS = "GET_PROPOSITIONS";
export const CREATE_PROPOSITION = "CREATE_PROPOSITION";
export const EDIT_PROPOSITION = "EDIT_PROPOSITION";
export const DELETE_PROPOSITION = "DELETE_PROPOSITION";
export const PROPOSITION_DETAIL = "PROPOSITION_DETAIL";

export const ALL_MISSIONS = "ALL_MISSIONS";
export const GET_MISSIONS = "GET_MISSIONS";
export const CREATE_MISSION = "CREATE_MISSION";
export const EDIT_MISSION = "EDIT_MISSION";
export const DELETE_MISSION = "DELETE_MISSION";
export const MISSION_DETAIL = "MISSION_DETAIL";

export const ALL_NOTIFICATIONS = "ALL_NOTIFICATIONS";
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const CREATE_NOTIFICATION = "CREATE_NOTIFICATION";
export const EDIT_NOTIFICATION = "EDIT_NOTIFICATION";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
export const NOTIFICATION_DETAIL = "NOTIFICATION_DETAIL";